include:
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

cache: &cache
  key:
    files:
      - ./yarn.lock
      - ./.yarnrc.yml
  paths:
    - ./.yarn/cache/
  policy: pull

default:
  image: ghcr.io/gulitsky/solidity-starter:latest
  tags:
    - build-solidity
  before_script:
    - YARN_CHECKSUM_BEHAVIOR=update yarn
    - yarn install --immutable
stages:
  - build
  - test
  - lint
  - release
  - deploy

build:
  stage: build
  script:
    - yarn run build
  cache:
    <<: *cache
    policy: pull-push
  artifacts:
    expire_in: 1 hour
    paths:
      - ./artifacts/

test:
  stage: test
  needs: ["build"]
  dependencies:
    - build
  cache:
    <<: *cache
  script:
    - yarn run test
  artifacts:
    when: always
    reports:
      junit: ./test-results.xml

coverage:
  stage: test
  needs: ["build"]
  cache:
    <<: *cache
  script:
    - yarn run coverage
  coverage: '/^Statements\s*:\s*([^%]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./coverage/cobertura-coverage.xml

lint:
  stage: lint
  needs: []
  cache:
    <<: *cache
  script:
    - yarn run lint
